from os.path import splitext

# cxx_binary(
#   name = 'gtx_associated_min_max',
#   srcs = [
#     'gtx_associated_min_max.cpp',
#   ],
#   deps = [
#     '//:glm',
#   ],
# )

tests = glob([
  '*.cpp',
])

for test in tests:
  cxx_binary(
    name = splitext(test)[0],
    srcs = [
      test,
    ],
    deps = [
      '//:glm',
    ],
  )
