from os.path import splitext

# cxx_binary(
#   name = 'gtc_bitfield',
#   srcs = [
#     'gtc_bitfield.cpp',
#   ],
#   deps = [
#     '//:glm',
#   ],
# )

tests = glob([
  '*.cpp',
])

for test in tests:
  cxx_binary(
    name = splitext(test)[0],
    srcs = [
      test,
    ],
    deps = [
      '//:glm',
    ],
  )
